[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "photometry"
version = "0.1.0"
description = "A collection of utilities for processing and analyzing photometry data"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["lmfit","matplotlib","pandas","h5py"]

[tool.setuptools.packages.find]
where = ["."]